### ISSUE TITLE
[Captcha]: Removal

### ISSUE THREAD

**Issue by Predeactor** [mrTownsend/mrTownsend-Cogs#2]
Hello,

I am the original creator of the Captcha cog. I've seen your repo and I am heavily against what you're doing. I've been letting the Captcha cog to @Kreusada because he's a known friend of mine, but I still technically own the cog and maintain it. I hope Kreusada will follow me in my procedure.
Your repo does not contain any license notice, and you've modified the `author`'s values in `info.json` to reflect you and your friend's names only, despite the fact that you're not the original author of the cog.

Quoting your README.md:
> [...] But as I move further and further away from your original code base, your credit will eventually be removed.

This is license breaching, everything you're taking from another open-source work that has a license MUST include the license, even if you have (heavily) modified the original code. No matter what. If you're doubting my words, please read the MIT license, which is one of the most permissive license available. (OSI approved)

I'm letting you personally 2 choices, the rest is to be handled by others developers, that I've alerted about your repo already:
1. You delete the Captcha cog from this repo.
2. You add the correct license for the Captcha cog (MIT license), see [Kreusada-Cogs license](https://github.com/Kreusada/Kreusada-Cogs/blob/master/LICENSE).

If you do not do anything in the following 14 days, I will have a deeper conversation with @Kreusada and we'll see what to do regarding your repository.

I also advise you to do the same for each cog you've replicated in this repository.

Thank you.

**Comment by mrTownsend** [comment]
Hello there, Predactor! Let me clarify for all PR - 

1.  I'm still **going to** place in here credit/licensing to the original creators, but I **will not be attributing any progress made on it to them** and **only** once **completely rewritten** will their credit tag be removed. Do you still say the plumber fixed your sink after you have to go back and do it again? No.  

2. My method of grabbing all of these repo's just to put them in one place was a very hack-job solution, and many files including licenses were not brought along. Solely the code that makes it function, that is it. Over the next coming days you will start to see them appear as I source them from the original author, as well as credit tags on the main module repository page. I am true to my word, I just realized that I didn't have the mental capacity at the time of writing said readme to go back and find all of those files. It was....4AM, more than likely and I was probably higher than a kite. 

3. If you have any further concerns please feel free to reply. I am not here trying to be a dickhead and rip other module owners. The RED community has a fantastic development base and there are many talented module owners and creators out there, and I'll be uploading my own originals as well. Many of the files have already had obvious changes to the authors and whatnot as I do prepare to make significant changes to them. You caught the painter before the paint was dry, I guess I could say.

Hope this clears any potential issues up. I'll be forwarding a copy of this to any collegues who reach out to me additionally. I am not here to create problems with you guys and once this is rectified I hope to continue to be an active contributor in the RED community. 

//C

**Comment by mrTownsend** [comment]
Per previous message, a license has been added. Thank you for reaching out, let me know if there's anything else I can do for you.

**Comment by Predeactor** [comment]
Hello,

I do not agree with your first point at all. 
> Do you still say the plumber fixed your sink after you have to go back and do it again? No.

First, we're +/- speaking about what's legal, not what's moral, and what's correct in the legal does not always have the greatest moral. Your example has no value, most especially when we're comparing computer's softwares and a physical service.

> I will not be attributing any progress made on it to them and only once completely rewritten will their credit tag be removed.

This is a completely no, you are using **OUR** code as a base, and in any absolute, once you are using our softwares, you have to also our licenses and apply all terms indicated in the license. No matter how many modifications you've done before, now, and in the future.

"You caught the painter before the paint was dry"
*desesperate sigh*

To follow #5, I'm now letting you 24h to setup a **correct** copy of the Kreusada-Cogs's license before I feel a DMCA to GitHub.

Thank you.

**Comment by mrTownsend** [comment]
The license has been pasted there. Please clarify how else I can help.

**Comment by Kreusada** [comment]
Please remove the rather irritating comment you've placed at the top of the LICENSE file. It contradicts your points found in the README.

**Comment by Predeactor** [comment]
I am not clarifying more. You had enough.
If you are struggling with my concerns, delete the cog and move on with the others.

**Comment by mrTownsend** [comment]
License modified. Thank you for actually answering my question instead of providing me a sarcastic, cunty reply. @Kreusada

**Comment by Kreusada** [comment]
I hope and know you realize that missing license attribution can cause developers great concern. Thanks for making an attempt to resolve this problem, please take care in the future when "taking" code from open source projects, no one should have to ask for attribution. 👍

**Comment by mrTownsend** [comment]
I'm aware of the importance of attribution. I have not only replied with a message that explained the issue but also taken time out of my day to fix it at your request. Thank you for your feedback.

**Comment by Kreusada** [comment]
Not having a go at you bud, you've responded well and I appreciate that. Thanks again for your changes.

**Comment by mrTownsend** [comment]
*sigh* Not that it is of any concern to you guys but like, the way this was addressed and spread to fellow developers didn't reflect what *caused* the LICENSES to not be there and thus combined with the changes to the author info, I get what it was looking like. At the same time however yknow, I now know exactly how fuckin nasty some of the glorified devs in the community are guessing from the lovely emails I've received off-site. 

Thanks for being cool man. LMK if there's anything i can do for u.

**Comment by Predeactor** [comment]
Hello @mrTownsend,

I would like to apologize for my replies (https://github.com/mrTownsend/mrTownsend-Cogs/issues/2#issuecomment-1025231392 & https://github.com/mrTownsend/mrTownsend-Cogs/issues/2#issuecomment-1025229862) that were quite unneeded (In term of wording). Please understand that it is the first time for me to face such context, so I also had to learnt, you're not the only one apparently. I also was reading everything when it was happening and I've been filled with many rage feeling all on me, which might not have been the most correct thing to do, I should have kept the issue on one cog only, and not trying to defend everyone. Happily enough, Kreusada reflected my wished on a more sympathic way.

I hope you'll take my excuses. We now have both to be ashamed of, but we've learnt and I hope both of us won't have to do such things again.
Just in top of that (Don't take it too personally), but even if someone replied you sharp, like I did, it's really unneeded to answer with such answer like "sarcastic, cunty reply.", also 95e43d0513f6139beaf431571375d82d33f1fd73 ("Just don't hassle me if you abandoned the project publicly a long time ago") (Would appreciate if you could remove that btw), you should've just ignored me on this one. Same goes on what you've wrote at first on the license. Personally, you're forgiven.

Also, could you please add @Kreusada's name and mine back to the `author`'s value in `info.json`? After then, we'll be officially done on both side. As such, this mean no DMCA request will be send if you respect my wish.

It's been a long night, I hope it'll not get more salt on it.

As for the DMCA request, this decision can be taken either by I or @Kreusada on our own discretion, but I think this won't be needed anymore.

Thank you.

**Comment by mrTownsend** [comment]
I'll address your points in a varying order. 

>Just in top of that (Don't take it too personally), but even if someone replied you sharp, like I did, it's really unneeded to answer with such answer like "sarcastic, cunty reply.", also 95e43d0 ("Just don't hassle me if you abandoned the project publicly a long time ago") (Would appreciate if you could remove that btw), you should've just ignored me on this one. Same goes on what you've wrote at first on the license.

I will attempt to be as fair as possible here.  You were my first point of contact via Discord, before I had gotten emails from GitHub. 
![Image1](https://i.imgur.com/poVxql0.png)

Which was very cordial, and I appreciated your professionalism. Then I check my GitHub dutifully, however...this is where you went off on the wrong foot. 

> 
> I'm letting you personally 2 choices, the rest is to be handled by others developers, that I've alerted about your repo already:
> 
> 1. You delete the Captcha cog from this repo.
> 2. You add the correct license for the Captcha cog (MIT license), see [Kreusada-Cogs license](https://github.com/Kreusada/Kreusada-Cogs/blob/master/LICENSE).
> 
> If you do not do anything in the following 14 days, I will have a deeper conversation with @Kreusada and we'll see what to do regarding your repository.
> 

No offense man but the animosity here is insulting. We're strangers - we'll interact best if we're friendly towards eachother. You're reached out to me as a stranger and given me an ultimatum which, for an ultimatum to work, typically demands respect if the person it's being given to has malicious intent. Since all I know you by is what is on your GitHub, then the question to be asked is if I respect your work or not. When you approach a stranger, especially with low information, don't come on the attack. It's very unbecoming. 

Second off, you completing what you felt was a duty to inform the Red development community of my heinous crimes against licenses, you started something of a developer witch hunt where I've received, besides the GitHub issues, emails, Discord messages, among other things. I even got a fucking twitter DM. ON A FOUR YEAR OLD ACCOUNT DUDE. An excessive and borderline-malicious-behavior-inducing decision. I did openly request for those who wanted credit to open an issue with me. That was there for a reason, simple as that. You assumed that I was a tool, doing something a tool would do. You made an assumption about a stranger who you also gave an ultimatum to. Not really....endearing. 


> I am not clarifying more. You had enough. If you are struggling with my concerns, delete the cog and move on with the others. (Or: I'm not wasting more time here)

This statement provides the assumption you believe I am lying to you, deceiving you, or acting stupid to mislead you and gives the impression you believe you are much more knowledgeable than me. Very condescending. You imply that your time is worth much more than mine and that it is a waste of your time to even speak to me. 

Moving on, for the best. 


Addressing your most recent message:

> Hello @mrTownsend,
> 
> I would like to apologize for my replies ([#2 (comment)](https://github.com/mrTownsend/mrTownsend-Cogs/issues/2#issuecomment-1025231392) & [#2 (comment)](https://github.com/mrTownsend/mrTownsend-Cogs/issues/2#issuecomment-1025229862)) that were quite unneeded (In term of wording). Please understand that it is the first time for me to face such context, so I also had to learnt, you're not the only one apparently. I also was reading everything when it was happening and I've been filled with many rage feeling all on me, which might not have been the most correct thing to do, I should have kept the issue on one cog only, and not trying to defend everyone. Happily enough, Kreusada reflected my wished on a more sympathic way.
> 
> I hope you'll take my excuses. We now have both to be ashamed of, but we've learnt and I hope both of us won't have to do such things again. Just in top of that (Don't take it too personally), but even if someone replied you sharp, like I did, it's really unneeded to answer with such answer like "sarcastic, cunty reply.", also [95e43d0](https://github.com/mrTownsend/mrTownsend-Cogs/commit/95e43d0513f6139beaf431571375d82d33f1fd73) ("Just don't hassle me if you abandoned the project publicly a long time ago") (Would appreciate if you could remove that btw), you should've just ignored me on this one. Same goes on what you've wrote at first on the license. Personally, you're forgiven.
> 
> Also, could you please add @Kreusada's name and mine back to the `author`'s value in `info.json`? After then, we'll be officially done on both side. As such, this mean no DMCA request will be send if you respect my wish.
> 
> It's been a long night, I hope it'll not get more salt on it.
> 
> As for the DMCA request, this decision can be taken either by I or @Kreusada on our own discretion, but I think this won't be needed anymore.
> 
> Thank you.

I appreciate your apology. I genuinely do. You're dutifully forgiven, but I ask that this not happen with anyone else again after this. 

I took a look at your [GitHub repository](https://github.com/Predeactor/Predeactor-Cogs#readme). Naturally, since you asked I remove something from mine I wondered why. It looks like you've abandoned your project `Predeactor-Cogs`, which I actually previously was not aware of. Another assumption you made about me is that I put that there directing it to you. I actually have been around the Red community, albeit on old accounts or not in the Discord, since back in the V2 days where it was very common to find repo's from talented developers who made great tools and then just...gave the fuck up man. And their great code, genuinely great quality cogs, just sat. And sat. And sat. It was a very common practice for me to have to pull cogs that hadn't been updated in 2+ years and take them apart and remake them because they were either no longer wholly compatible, or had failing dependencies, or other various errors and bugs. So...look. I think you're a talented developer. I'm not sure what's going on in your life right now and what caused you to want to give up, but I hope you come back. Doesn't have to be right now. Maybe in two weeks, or a month. You're the most important thing to you, so take time, please do. But you're too talented to abandon development and I hope if you didn't realize that or believe it, that hearing it from a stranger changes your mind. 

I don't believe either of us have anything to be ashamed of here. I made an honest mistake. You let emotion get the best of you. These are not shameful things, they are learning experiences and I do hope that we've learned from today. As far as the sarcastic and cunty reply, I already detailed how condescending it was so while I apologize for the spice, it had been dually earned at the time considering your perceived attitude. 

As far as adding credit to the actual `info.json`, I can gladly do this. Thank you for reminding me/letting me know. 

As for the DMCA Request - with either of you, I am more than willing to continue the conversation to avoid that. 

In the future, just some suggestions about how you could better handle situations where licenses/work have been removed (all be it intentionally or unintentionally)

1. Submit a PR Request adding the LICENSE and modifying the `info.json`. Note in the comments that you're the original owner/developer/copyright owner/etc and are requesting they make those changes. It's a very non-offensive way to strongly suggest the right thing be done. You're giving them the option to fix it with the click of a button in a non-offensive way. Yes, I know, it's maybe a minute or two of work you don't have to do but genuinely it is the less confrontational thing to do. If you had done that, I would have clicked accept and it would have been done with in 2 seconds. We wouldn't have gotten heated. 
2. If the PR Request is denied and it's blatantly obvious that it is code you own the rights to, create an issue with a very open-ended and friendly script. 
"Hello there user! I'm user, the original creator of (link), which you have hosted on your GitHub. I noticed that in your `info.json` and in your `modulefile.py`, you have changed the author to your own name. Since you haven't made what I believe are a fair amount of changes to my work, I'd like to see what we can do to get this fixed". 
3. Give it 72 hours. Issue then a DMCA Warning. 

Taking that extra, non-confrontational step will avoid situations like this entirely. 

All of this being said, thank you for again reaching out to me with, what I hope were good intentions. Shit happens, but I hold no ill will towards any of you. If there's anything I can do for you guys, or either of you want to make a new friend or need someone to talk to or you know, idk human things...just let me know. You know where to find me. 

//C

**Comment by mrTownsend** [comment]
I have made additional changes at [fcbdeb85036626ad706e18c6cae87375dcbb233d](http://github.com/mrTownsend-Cogs/captcha/info.json] that I believe you will both find satisfactory. Thank you for reaching out, I'll close this issue now. <3
